export const CREATE_PRODUCT_REQUEST =  'CREATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_REQUEST =  'UPDATE_PRODUCT_REQUEST';
export const GET_PRODUCT_REQUEST =  'GET_PRODUCT_REQUEST';
export const GET_PRODUCTS_REQUEST =  'GET_PRODUCTS_REQUEST';
export const REMOVE_PRODUCT_REQUEST =  'REMOVE_PRODUCT_REQUEST';