export const REGISTER_MODAL_SHOW =  'REGISTER_MODAL_SHOW';
export const LOGIN_MODAL_SHOW =  'LOGIN_MODAL_SHOW';
export const FORGOT_PASS_MODAL_SHOW =  'FORGOT_PASS_MODAL_SHOW';
export const CLOSE_ALL_AUTH_MODAL_SHOW =  'CLOSE_ALL_AUTH_MODAL_SHOW';