export const LOGIN_REQUEST =  'LOGIN_REQUEST';
export const LOGOUT =  'LOGOUT';
export const LOGIN_SUCCESS =  'LOGIN_SUCCESS';
export const REGISTER_REQUEST =  'REGISTER_REQUEST';
export const FORGOT_PASSWORD_MESSAGE =  'FORGOT_PASSWORD_MESSAGE';
export const RECIEVED_NEW_PASS_MESSAGE =  'RECIEVED_NEW_PASS_MESSAGE';