export const ADD_PRODUCT_CART =  'ADD_PRODUCT_CART';
export const REMOVE_PRODUCT_CART =  'REMOVE_PRODUCT_CART';
export const GET_CART =  'GET_CART';
export const UPDATE_QUANTITY_ITEM_CART =  'UPDATE_QUANTITY_ITEM_CART';