export const CREATE_COLOR_REQUEST =  'CREATE_COLOR_REQUEST';
export const UPDATE_COLOR_REQUEST =  'UPDATE_COLOR_REQUEST';
export const GET_COLOR_REQUEST =  'GET_COLOR_REQUEST';
export const GET_COLORS_REQUEST =  'GET_COLORS_REQUEST';
export const REMOVE_COLOR_REQUEST =  'REMOVE_COLOR_REQUEST';